#!/bin/sh

case "$1" in
    start)
        echo "USB initialize..."
        insmod /lib/modules/`uname -r`/kernel/drivers/usb/host/ehci-hcd.ko
        insmod /lib/modules/`uname -r`/kernel/drivers/usb/host/ohci-hcd.ko
    ;;
esac
