#!/bin/sh

case "$1" in
    start)
        if [ ! -c /dev/gxav0 ]; then
            echo "Install gxavdev driver..."
            mknod /dev/gxav0 c 122 0
            insmod /lib/modules/`uname -r`/av.ko
        fi
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
